import Head from 'next/head'
import Opening from '../components/opening'

export default function Home() {
  return (
    <div>
      <Head>
        <title>REFORGED MU ONLINE Season 18 Episodio 1-3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black">
        <Opening />
      </main>

    </div>
  )
}
